apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: my-postgres-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432