replicaCount: 1
image:
  repository: my-postgres-db
  tag: latest
  pullPolicy: Never

postgres:
  user: myuser
  password: mypassword
  database: mydb

service:
  type: ClusterIP
  port: 5432

nameOverride: "postgres-demo-postgres"
fullnameOverride: "postgres-demo-postgres"

labels:
  app: postgres-demo-postgres

podLabels:
  app: postgres-demo-postgres